package de.hbrs.se2.womm.views.extra;
import java.util.HashMap;
import java.util.Map;
public class TranslateMap {
    public static Map<String, String> translateMap = new HashMap<>();
    static {
        translateMap.put("", "");
        translateMap.put("Your job search portal. Discover thousands of job opportunities and more.", "Dein Jobportal. Entdecke tausende Jobangebote und mehr.");
        translateMap.put("SignUp as Student", "Registriere dich als Student");
        translateMap.put("SignUp as Company", "Registriere dich als Unternehmen");
        translateMap.put("Find your dream job on w.o.m.m.", "Finde deinen Traumjob auf w.o.m.m.");
        translateMap.put("Want to create company profile? Contact us at kontakt@womm.de.", "Möchtest du ein Firmenprofil erstellen? Kontaktiere uns unter kontakt@womm.de.");
        translateMap.put("LogIn", "Anmelden");
        translateMap.put("Create advertisement", "Stellenanzeige erstellen");
        translateMap.put("View applications", "Bewerbungen anschauen");
        translateMap.put("Filter by...", "Filter nach...");
        translateMap.put("Advertisement title", "Name Stellenanzeige"); 
        translateMap.put("Firm name", "Name Unternehmen"); 
        translateMap.put("Home", "Startseite");
        translateMap.put("Name", "Name");
        translateMap.put("Enter keyword", "Stichwort eingeben");
        translateMap.put("Subscriptions", "Abonnements");
        translateMap.put("UChatView", "Chat");
        translateMap.put("UEditFirmProfileDisplayView", "Profil editieren");
        translateMap.put("UFirmProfileDisplayView", "Profil");
        translateMap.put("UHomepageUnternehmenView", "Homepage");
        translateMap.put("UStelleAnzeigeErstellenView", "Stellenanzeige erstellen");
        translateMap.put("UApplicationView", "Bewerbung");
        translateMap.put("UNotificationView", "Benachrichtigungen");
        translateMap.put("UApplicationsView", "Bewerbungen");
        translateMap.put("SJobProjectWorkshopDisplayView", "Stellenanzeigen(delete link)");
        translateMap.put("SStudentProfileDisplayView", "Profil");
        translateMap.put("SCreateChangeStudentProfileView", "Profil editieren");
        translateMap.put("SApplicationView", "Bewerbung (delete link)");
        translateMap.put("SHomepageStudentView", "Homepage");
        translateMap.put("SNotificationView", "Benachrichtigungen");
        translateMap.put("SAboStudentView", "Abonnements");
        translateMap.put("SChatView", "Chat");
        translateMap.put("Search", "Suche");
        translateMap.put("Chat", "Chat");
        translateMap.put("SFirmProfileDisplayView", "Firmenprofil(delete link)");
        translateMap.put("View subscriptions", "Abonnements anzeigen");
        translateMap.put("Notifications", "Benachrichtigungen");
        translateMap.put("Edit profile", "Profil bearbeiten");
        translateMap.put("%s is not a valid ID.", "%s ist keine gültige ID.");
        translateMap.put("Surname, Name", "Name, Vorname");
        translateMap.put("Motivational letter", "Anschreiben");
        translateMap.put("The application with the ID '%s' could not be found.", "Die Bewerbung mit der ID '%s' konnte nicht gefunden werden.");
        translateMap.put("Access Denied!", "Zugriff verweigert!");
        translateMap.put("Confirm Password", "Passwort bestätigen");
        translateMap.put("Password is required", "Passwort ist erforderlich");
        translateMap.put("Email connected to your future account", "Email, die mit Ihrem zukünftigen Konto verbunden ist");
        translateMap.put("Invalid date given. Dates must follow the 'DD.MM.YYYY' format.", "Ungültiges Datum angegeben. Daten müssen dem Format 'TT.MM.JJJJ' folgen.");
        translateMap.put("Password Confirmation is required", "Passwortbestätigung ist erforderlich");
        translateMap.put("Repeat your password", "Wiederholen Sie Ihr Passwort");
        translateMap.put("Email is required", "Email ist erforderlich");
        translateMap.put("Select your date of birth", "Wählen Sie Ihr Geburtsdatum");
        translateMap.put("Your desired username", "Ihr gewünschter Benutzername");
        translateMap.put("Password", "Passwort");
        translateMap.put("Username is required", "Benutzername ist erforderlich");
        translateMap.put("Your REAL surname", "Ihr ECHTER Nachname");
        translateMap.put("Email 😳", "Email 😳");
        translateMap.put("Location is required", "Standort ist erforderlich");
        translateMap.put("Your REAL Name", "Ihr ECHTER Name");
        translateMap.put("Your REAL Company Name", "Ihr ECHTER Unternehmensname");
        translateMap.put("The password used for login", "Das Passwort für die Anmeldung");
        translateMap.put("Surname is required", "Nachname ist erforderlich");
        translateMap.put("Student/in Registration", "Student/in Registrierung");
        translateMap.put("Company Registration", "Unternehmen Registrierung");
        translateMap.put("Your current living location", "Ihr aktueller Wohnort");
        translateMap.put("Company Name is required", "Name Ihres Unternehmens ist erforderlich");
        translateMap.put("Name is required", "Name ist erforderlich");
        translateMap.put("Username", "Benutzername");
        translateMap.put("Register", "Registrieren");
        translateMap.put("Surname", "Nachname");
        translateMap.put("Company Name", "Name Ihres Unternehmens");
        translateMap.put("Location", "Ort");
        translateMap.put("Date of Birth", "Geburtstag");
        translateMap.put("e-mail", "E-Mail");
        translateMap.put("E-Mail Address", "E-Mail-Adresse");
        translateMap.put("alias", "Alias");
        translateMap.put("Current semester", "Aktuelles Semester");
        translateMap.put("Specializations", "Spezialisierungen");
        translateMap.put("Biography", "Biographie");
        translateMap.put("Enter your old password", "Altes Passwort");
        translateMap.put("Save Changes", "Änderungen Speichern");
        translateMap.put("Please enter a valid e-mail address", "Bitte eine gültige E-Mail-Adresse angeben");
        translateMap.put("Upload", "Hochladen");
        translateMap.put("The name can only be changed with the agreement of an admin", "Der Name kann nur mit Absprache eines Admins geändert werden");
        translateMap.put("Confirm e-mail", "E-Mail bestätigen");
        translateMap.put("I am in semester:", "Ich bin in Semester:");
        translateMap.put("Repeat your new password", "Neues Passwort wiederholen");
        translateMap.put("Push Notifications", "Benachrichtigungen");
        translateMap.put("Your password must have 6 to 12 characters. Only letters A-Z and numbers supported.", "Das neue Passwort muss eine Länge von 6 bis 12 Zeichen haben und darf nur Buchstaben von A bis Z und Zahlen beeinhalten");
        translateMap.put("I would like to receive notifications", "Ich möchte Benachrichtigungen erhalten");
        translateMap.put("Enter your new password", "Neues Passwort");
        translateMap.put("Please enter your current valid Password", "Bitte gib dein aktuelles Passwort ein");
        translateMap.put("Please enter your new valid Password", "Bitte gib dein neues, gültiges Passwort ein");
        translateMap.put("Please re-enter your new valid Password", "Bitte wiederhole dein neues, gültiges Passwort");
        translateMap.put("Please enter your current semester", "Bitte gib dein aktuelles Semester ein");
        translateMap.put("Please re-enter your valid e-mail address", "Bitte wiederhole deine gültige E-Mail-Adresse");
        translateMap.put("Semester", "Semester");
        translateMap.put("Curriculum Vitae", "Lebenslauf");
        translateMap.put("Changes saved!", "Änderungen gespeichert!");
        translateMap.put("The job offer is not available anymore :(", "Das Stellenangebot existiert nicht mehr :(");
        translateMap.put("Please enter your application into the text field!", "Trage bitte dein Anschreiben in das Feld ein!");
        translateMap.put("Send", "Abschicken");
        translateMap.put("Write a short application here", "Schreibe ein kurzes Anschreiben für deine Bewerbung");
        translateMap.put("Apply now", "Jetzt bewerben");
        translateMap.put("Apply later", "Später bewerben");
        translateMap.put("Your application has been sent successfully", "Deine Bewerbung wurde erfolgreich versendet");
        translateMap.put("Accept", "Annehmen");
        translateMap.put("Decline", "Ablehnen");
        translateMap.put("You have accepted the application", "Sie haben die Bewerbung angenommen");
        translateMap.put("You have declined the application", "Sie haben die Bewerbung abgelehnt");
        translateMap.put("SApplicationsView", "Bewerbungen");
        translateMap.put("Log out(", "Ausloggen(");
        translateMap.put("Log out", "Ausloggen");
        translateMap.put("Your application has been accepted.", "Ihre Bewerbung wurde akzeptiert.");
        translateMap.put("Your application has been delcined.", "Ihre Bewerbung wurde abgelehnt.");
        translateMap.put("Your application is awaiting review.", "Ihre Bewerbung befindet sich in Bearbeitung.");
        translateMap.put("Your motivational letter:", "Ihr Anschreiben:");
        translateMap.put("Application photo", "Bewerbungsfoto");
        translateMap.put("Application text", "Bewerbungs-Text");
        translateMap.put("New Jobs from your subscribed companies", "Neue Stellenangebote von deinen abonnierten Unternehmen");
    }
}
