package tools.collection;

public class StellenNames {

    public static String[] listOfRandomStellenBezeichnungen = {
            "Java Software Engineer",
            "Software Engineer",
            "Enterprise Application Software Engineer - 35177764",
            "Sr. Full Stack Software Engineer (JavaScript)",
            "VP of Technology",
            "JavaScript Engineer",
            "Chief Technology Officer",
            "Senior Full Stack Developer (HTML5, CSS3, JS, Ruby)",
            "Software Engineer/Web Application Developer",
            "iOS Developer",
            "Senior Software Developer",
            "Software Developer",
            "User Interface Developer",
            "Senior Full-Stack Engineer - Ruby on Rails (Technical Lead)",
            "Frontend Software Engineer (Content Authoring Tools)",
            "Senior Backend Engineer (Architecture & Maintenance)",
            "DevOps Engineer",
            "Lead Frontend Developer",
            "Lead PHP Backend Developer",
            "Senior Frontend Engineer",
            "Senior Backend Engineer (Feature Development)",
            "Senior PHP Backend Developer",
            " VP of Engineering",
            "Experienced Security People (SF)",
            "Web Applications Developer",
            "Android Mobile Engineer",
            "Software Engineer / Ruby on Rails Developer",
            "Python/JavaScript software developer in open source project",
            "SOFTWARE-INGENIEUR / E-COMMERCE (80 – 100 %)",
            "Cloud Engineer",
            "Software Build Engineer",
            "Software Engineer",
            "Engineering Manager, Web UI",
            "Software Engineer, Advanced High Throughput Services",
            "Site Reliability Engineer - 33891662",
            "Frontend Specialist  ",
            "Senior Java/Android Developer",
            "Senior Software Engineer",
            "DevOps Engineer",
            "Content Delivery Interconnections Manager",
            "Lean/Agile Coach",
            "Software Engineer | Maps & Geo",
            "Unix System Administrator",
            "Unix System Administrator",
            "iOS Developer",
            "Team Lead Development",
            "Perl Developer",
            "Experienced Software Developer - willing to learn Perl",
            "Developer (Ruby on Rails)",
            "Senior Front End Developer",
    };
}
