package tools.collection;

import java.util.Random;

public class Tags {

    public static String getRandomTag() {
        int randomInt = new Random().nextInt(0, listOfRandomItems.length);
        return listOfRandomItems[randomInt];
    }
    public static String getRandomSpez() {
        int randomInt = new Random().nextInt(0, listOfRandomSpez.length);
        return listOfRandomSpez[randomInt];
    }
    private static String[] listOfRandomSpez = {
            "Komplexe Softwaresysteme",
            "It-Security",
            "Wirtschaftsinformatik",
            "AI",
            "Data Science",
    };


    private static String[] listOfRandomItems = {
            "Java",
            "C++",
            "C#",
            "Python",
            "JavaScript",
            "HTML",
            "CSS",
            "PHP",
            "SQL",
            "TypeScript",
            "Ruby",
            "Swift",
            "Kotlin",
            "Go",
            "R",
            "VBA",
            "Objective-C",
            "Scala",
            "Perl",
            "Rust",
            "Dart",
            "Haskell",
            "Lua",
            "ABAP",
            "Delphi",
            "Julia",
            "Groovy",
            "PowerShell",
            "Assembly",
            "MATLAB",
            "Visual Basic",
            "PL/SQL",
            "Transact-SQL",
            "D",
            "COBOL",
            "Apex",
            "Fortran",
            "Lisp",
            "Scheme",
            "Ada",
            "F#",
            "Clojure",
            "Logo",
            "LabVIEW",
            "Prolog",
            "Scratch",
            "Alice",
            "RPG",
            "ABAP",
            "Apex",
            "C",
            "C#",
            "C++",
            "COBOL",
            "Delphi",
            "Fortran",
            "Go",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Julia",
            "Kotlin",
            "LabVIEW",
            "Lisp",
            "Logo",
            "Lua",
            "MATLAB",
            "Objective-C",
            "Pascal",
            "Perl",
            "PHP",
            "PL/SQL",
            "PowerShell",
            "Prolog",
            "Python",
            "R",
            "RPG",
            "Ruby",
            "Rust",
            "Scala",
            "Scheme",
            "Scratch",
            "SQL",
            "Swift",
            "Transact-SQL",
            "TypeScript",
            "Visual Basic",
            "VBA",
            "D",
            "F#",
            "ABAP",
            "Apex",
            "C",
            "C#",
            "C++",
            "COBOL",
            "Delphi",
            "Fortran",
            "Go",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Julia",
            "Kotlin",
    };
}
