package tools.collection;

import java.util.Random;

public class UnternehmenAndWebsites {

    private static String getRandomUnternehmenAndWebsites(int unternehmen0OrWebsite1){
        int randomInt = new Random().nextInt(0, UnternehmenNamesAndWebsite.length);
        return UnternehmenNamesAndWebsite[randomInt][unternehmen0OrWebsite1];
    }
    public static String getRandomUnternehmenName() {
        return getRandomUnternehmenAndWebsites(0);
    }
    public static String getRandomWebsite() {
        return getRandomUnternehmenAndWebsites(1);
    }

    public static String[][] UnternehmenNamesAndWebsite = new String[][]{
            {"Walmart	", "https://www.walmart.com/"},
            {"Amazon	", "https://www.amazon.com/"},
            {"Exxon Mobil	", "https://corporate.exxonmobil.com/"},
            {"Apple	", "https://www.apple.com/"},
            {"UnitedHealth Group	", "https://www.unitedhealthgroup.com/"},
            {"CVS Health	", "https://www.cvshealth.com/"},
            {"Berkshire Hathaway	", "https://www.berkshirehathaway.com/"},
            {"Alphabet	", "https://abc.xyz/"},
            {"McKesson	", "https://www.mckesson.com/"},
            {"Chevron	", "https://www.chevron.com/"},
            {"AmerisourceBergen	", "https://www.amerisourcebergen.com/"},
            {"Costco Wholesale	", "https://www.costco.com/"},
            {"Microsoft	", "https://www.microsoft.com/"},
            {"Cardinal Health	", "https://www.cardinalhealth.com/"},
            {"Cigna	", "https://www.cigna.com/"},
            {"Marathon Petroleum	", "https://www.marathonpetroleum.com/"},
            {"Phillips 66	", "https://www.phillips66.com/"},
            {"Valero Energy	", "https://www.valero.com/"},
            {"Ford Motor	", "https://www.ford.com/"},
            {"Home Depot	", "https://www.homedepot.com/"},
            {"General Motors	", "https://www.gm.com/"},
            {"Elevance Health	", "https://www.elevancehealth.com/"},
            {"JPMorgan Chase	", "https://www.jpmorganchase.com/"},
            {"Kroger	", "https://www.kroger.com/"},
            {"Centene	", "https://www.centene.com/"},
            {"Verizon Communications	", "https://www.verizon.com/"},
            {"Walgreens Boots Alliance	", "https://www.walgreensbootsalliance.com/"},
            {"Fannie Mae	", "https://www.fanniemae.com/"},
            {"Comcast	", "https://corporate.comcast.com/"},
            {"AT&T	", "https://www.att.com"},
            {"Meta Platforms	", "https://about.facebook.com/"},
            {"Bank of America	", "https://www.bankofamerica.com/"},
            {"Target	", "https://www.target.com/"},
            {"Dell Technologies	", "https://www.dell.com/"},
            {"Archer Daniels Midland	", "https://www.adm.com/"},
            {"Citigroup	", "https://www.citigroup.com/"},
            {"UPS	", "https://www.ups.com/"},
            {"Pfizer	", "https://www.pfizer.com/"},
            {"Lowe's	", "https://www.lowes.com/"},
            {"Johnson & Johnson	", "https://www.jnj.com/"},
            {"FedEx	", "https://www.fedex.com/"},
            {"Humana	", "https://www.humana.com/"},
            {"Energy Transfer	", "https://www.energytransfer.com/"},
            {"State Farm Insurance	", "https://www.statefarm.com/"},
            {"Freddie Mac	", "https://www.freddiemac.com/"},
            {"PepsiCo	", "https://www.pepsico.com/"},
            {"Wells Fargo	", "https://www.wellsfargo.com/"},
            {"Walt Disney	", "https://thewaltdisneycompany.com/"},
            {"ConocoPhillips	", "https://www.conocophillips.com/"},
            {"Tesla	", "https://www.tesla.com/"},
            {"Procter & Gamble	", "https://www.pg.co.uk/"},
            {"General Electric	", "https://www.ge.com/"},
            {"Albertsons	", "https://www.albertsons.com/"},
            {"MetLife	", "https://www.metlife.com/"},
            {"Goldman Sachs Group	", "https://www.goldmansachs.com/"},
            {"Sysco	", "https://www.sysco.com/"},
            {"Raytheon Technologies	", "https://www.rtx.com/"},
            {"Boeing	", "https://www.boeing.com/"},
            {"StoneX Group	", "https://www.stonex.com/"},
            {"Lockheed Martin	", "https://www.lockheedmartin.com/"},
            {"Morgan Stanley	", "https://www.morganstanley.com/"},
            {"Intel	", "https://www.intel.com"},
            {"HP	", "https://www.hp.com/"},
            {"TD Synnex	", "https://www.tdsynnex.com/"},
            {"IBM	", "https://www.ibm.com/"},
            {"HCA Healthcare", "www.hcahealthcare.com"},
            {"Prudential Financial	", "https://www.prudential.com/"},
            {"Caterpillar	", "https://www.caterpillar.com/"},
            {"Merck	", "https://www.merck.com/"},
            {"World Kinect	", "https://www.world-kinect.com/"},
            {"New York Life Insurance	", "https://www.newyorklife.com/"},
            {"Enterprise Products Partners", "www.enterpriseproducts.com"},
            {"AbbVie	", "https://www.abbvie.com/"},
            {"Plains GP Holdings	", "https://www.plains.com/"},
            {"Dow	", "https://www.dow.com/"},
            {"AIG	", "https://www.aig.com/"},
            {"American Express	", "https://www.americanexpress.com/"},
            {"Publix Super Markets	", "https://www.publix.com/"},
            {"Charter Communications	", "https://corporate.charter.com/"},
            {"Tyson Foods	", "https://www.tysonfoods.com/"},
            {"Deere	", "https://www.deere.com/"},
            {"Cisco Systems	", "https://www.cisco.com/"},
            {"Nationwide	", "https://www.nationwide.com/"},
            {"Allstate	", "https://www.allstate.com/"},
            {"Delta Air Lines	", "https://www.delta.com/"},
            {"Liberty Mutual Insurance Group	", "https://www.libertymutualgroup.com/"},
            {"TJX	", "https://www.tjx.com/"},
            {"Progressive	", "https://www.progressive.com/"},
            {"American Airlines Group	", "https://www.aa.com/"},
            {"CHS	", "https://www.chsinc.com/"},
            {"Performance Food Group	", "https://www.pfgc.com/"},
            {"PBF Energy	", "https://www.pbfenergy.com/"},
            {"Nike	", "https://www.nike.com/"},
            {"Best Buy	", "https://www.bestbuy.com/"},
            {"Bristol-Myers Squibb	", "https://www.bms.com/"},
            {"United Airlines Holdings	", "https://ir.united.com/"},
            {"Thermo Fisher Scientific	", "https://www.thermofisher.com/"},
            {"Qualcomm	", "https://www.qualcomm.com/"},
            {"Abbott Laboratories	", "https://www.abbott.com/"},
            {"Coca-Cola	", "https://www.coca-colacompany.com/"},

    };
}

